export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api';
export const FILE_BASE_URL = import.meta.env.VITE_FILE_BASE_URL || (import.meta.env.VITE_API_BASE_URL ? import.meta.env.VITE_API_BASE_URL.replace('/api', '') : 'http://localhost:8080');

export const LOST_ITEM_STATUSES = ['OPEN', 'MATCH_FOUND', 'CLAIM_IN_PROGRESS', 'RECOVERED', 'CLOSED'];
export const FOUND_ITEM_STATUSES = ['AVAILABLE', 'CLAIM_REQUESTED', 'UNDER_VERIFICATION', 'APPROVED_FOR_RETURN', 'RETURNED', 'CLOSED'];
export const CLAIM_STATUSES = ['PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'HANDOVER_PENDING', 'FINDER_CONFIRMED', 'OWNER_CONFIRMED', 'RETURNED', 'CLOSED'];

export const STATUS_COLORS = {
  OPEN: '#3b82f6', AVAILABLE: '#22c55e', PENDING: '#f59e0b',
  MATCH_FOUND: '#8b5cf6', CLAIM_REQUESTED: '#f97316', UNDER_REVIEW: '#6366f1',
  CLAIM_IN_PROGRESS: '#f59e0b', UNDER_VERIFICATION: '#06b6d4', APPROVED_FOR_RETURN: '#0284c7',
  APPROVED: '#22c55e', REJECTED: '#ef4444', HANDOVER_PENDING: '#8b5cf6',
  FINDER_CONFIRMED: '#10b981', OWNER_CONFIRMED: '#10b981',
  RECOVERED: '#22c55e', RETURNED: '#059669', CLOSED: '#6b7280',
  REVIEWED: '#3b82f6', RESOLVED: '#22c55e', DISMISSED: '#6b7280',
};
